In [1]:
import numpy as np

In [2]:
a = np.array([[1, 0, -1],
              [2, 2, -3],
              [3, 4, 0]])
b = np.array([[3, 4, -1],
              [1, -3, 0],
              [-1, 1, 2]])
a+b


array([[ 4,  4, -2],
       [ 3, -1, -3],
       [ 2,  5,  2]])

In [5]:
# 矩阵乘法
a = np.array([[1, 0, 4],
              [2, 1, 1],
              [3, 1, 0],
              [0, 2, 2]
              ])
b = np.array([[2, 4],
              [1, 1],
              [3, 0],
              ])
print(f'a:{a}')
print(f'b:{b}')
a@b


a:[[1 0 4]
 [2 1 1]
 [3 1 0]
 [0 2 2]]
b:[[2 4]
 [1 1]
 [3 0]]


array([[14,  4],
       [ 8,  9],
       [ 7, 13],
       [ 8,  2]])

In [6]:
# 矩阵转置
a.T

array([[1, 2, 3, 0],
       [0, 1, 1, 2],
       [4, 1, 0, 2]])

In [9]:
square = np.array([[1, 1, 0],
                   [1, 0, 1],
                   [0, 1, 0]])
print(f'square:{square}')
square.T


square:[[1 1 0]
 [1 0 1]
 [0 1 0]]


array([[1, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [10]:
# 矩阵的交集和并集
A = np.array([[1, 0, 1],
              [0, 1, 0]])
B = np.array([[0, 1, 0],
              [1, 1, 0]])
print(f'A={A}')
print(f'B={B}')
A | B


A=[[1 0 1]
 [0 1 0]]
B=[[0 1 0]
 [1 1 0]]


array([[1, 1, 1],
       [1, 1, 0]])

In [11]:
A&B

array([[0, 0, 0],
       [0, 1, 0]])

In [71]:
# 针对0-1矩阵的布尔乘积，也就是矩阵的乘积
A = np.array([[1, 0],
              [0, 1],
              [1, 0]
              ])
B = np.array([[1, 1, 0],
              [0, 1, 1],
              ])
print(f'A={A}')
print(f'B={B}')
A@B
# np.dot(A,B)



A=[[1 0]
 [0 1]
 [1 0]]
B=[[1 1 0]
 [0 1 1]]


array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 0]])

In [73]:
A = np.array([[0, 0, 1],
              [1, 0, 0],
              [1, 1, 0]
              ])
print(f'A={A}')

# def bool_power(arr:np.ndarray,n:int):
#     res=arr
#     for i in range(n-1):
#         res=np.dot(res,arr)
#     return res
# bool_power(A,5)
# np.power(A,6)

np.linalg.matrix_power(A,5)


A=[[0 0 1]
 [1 0 0]
 [1 1 0]]


array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])